[BREAKING] Change image name and add SemVer.
Details see CHANGELOG entry.

diff --git a/.github/workflows/docker_publish.yml b/.github/workflows/docker_publish.yml
--- a/.github/workflows/docker_publish.yml
+++ b/.github/workflows/docker_publish.yml
@@ -2,19 +2,13 @@ name: Docker
 
 on:
   push:
-    # Publish `main` as Docker `latest` image.
-    branches:
-      - main
-
-    # Publish `v1.2.3` tags as releases.
     tags:
       - v*
 
-  # Run tests for any PRs.
-  pull_request:
-
 env:
-  IMAGE_NAME: nginx-typo3-base
+  IMAGE_NAME: typo3_base
+  OWNER: rintisch
+  REGISTRY: ghcr.io
 
 jobs:
   # Push image to GitHub Packages.
@@ -33,27 +27,49 @@ jobs:
       - name: Build image
         run: docker build . --file Dockerfile --tag $IMAGE_NAME 
 
-      - name: Log into registry
-        run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
+      - name: Login to GitHub Container Registry
+        run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
 
-      - name: Push Image to registry
+      - name: Push images - same image with different versions (major, minor, patch & latest)
         run: |
-          IMAGE_ID_LIVE=ghcr.io/${{ github.repository }}/$IMAGE_NAME
-
+          IMAGE_ID_LIVE=ghcr.io/$OWNER/$IMAGE_NAME
+          
           # Change all uppercase to lowercase
           IMAGE_ID_LIVE=$(echo $IMAGE_ID_LIVE | tr '[A-Z]' '[a-z]')
 
-          # Strip git ref prefix from version
-          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
+          # Strip git ref prefix from version (e.g. `refs/heads/main` becomes `main`)
+          VERSION_RAW=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
 
-          # Strip "v" prefix from tag name
-          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
+          # Strip "v" prefix from tag name (e.g. `v1.2.0` becomes `1.2.0`)
+          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION_RAW=$(echo $VERSION_RAW | sed -e 's/^v//')
+          
+          # Test that version number is valid
+          REGEXP='^([0-9]+\.){2}(\*|[0-9]+)$'
+          if [[ $VERSION_RAW =~ $REGEXP ]]
+          then
+            echo "SUCCESS: '$VERSION_RAW' is a valid version number."
+          else
+            echo "ERROR: '$VERSION_RAW' is not a valid version number."
+            exit 1
+          fi
+          
+          # Create needed version numbers
+          VERSION_ARRAY=( ${VERSION_RAW//./ } )
+          VERSION_MAIN=${VERSION_ARRAY[0]}
+          VERSION_MINOR=${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}
+          VERSION_PATCH=${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.${VERSION_ARRAY[2]}
+          VERSION_LATEST='latest'
 
-          # Use Docker `latest` tag convention
-          [ "$VERSION" == "main" ] && VERSION=latest
-
-          echo IMAGE_ID_LIVE=$IMAGE_ID_LIVE
-          echo VERSION=$VERSION
-
-          docker tag $IMAGE_NAME $IMAGE_ID_LIVE:$VERSION
-          docker push $IMAGE_ID_LIVE:$VERSION
+          echo IMAGE_ID_LIVE =  $IMAGE_ID_LIVE
+          echo VERSION_LATEST = $VERSION_LATEST
+          echo VERSION_MAIN =   $VERSION_MAIN
+          echo VERSION_MINOR =  $VERSION_MINOR
+          echo VERSION_PATCH =  $VERSION_PATCH
+          
+          docker image tag $IMAGE_NAME $IMAGE_ID_LIVE:$VERSION_MAIN
+          docker image tag $IMAGE_NAME $IMAGE_ID_LIVE:$VERSION_MINOR
+          docker image tag $IMAGE_NAME $IMAGE_ID_LIVE:$VERSION_PATCH
+          docker image tag $IMAGE_NAME $IMAGE_ID_LIVE:$VERSION_LATEST
+          
+          docker image ls
+          docker image push --all-tags $IMAGE_ID_LIVE
